version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27999:27017"
  Eureka:
    container_name: eureka
    build: .\eurekaDiscov
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: "eureka"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
  Reservation:
    container_name: Reservation
    build: .\reservation-ms-expressjs
    hostname: reservationhost
    ports:
      - "3086:8086"
    environment:
      - MONGO_URI=mongodb://mongo:27017/reservation
      - EUREKA_CLIENT_HOST=serviceregistry
      - APP_HOST=reservationhost
      - APP_IP_ADRESS=localhost
    image: "reservation-ms-expressjs"
    restart: always
    depends_on:
      - Eureka
      - mongo
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
      #- MYSQL_DATABASE=job
    ports:
      - "3306:3306"
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8306:80"
    links:
      - db-mysql:db
    depends_on:
      - db-mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    hostname: keycloakauth
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
  Gateway:
    container_name: Gateway
    image: "gateway"
    build: .\gateway
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloakauth:8080/realms/Enigma
    depends_on:
      - "Eureka"
      - "Foyer"
      - "Universite"
      - "keycloak"
  Universite:
    container_name: Universite
    build: .\universite-ms
    ports:
      - "3082:8082"
    environment:
      #port 8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/universite-ms?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "universite-ms"
    restart: unless-stopped
    depends_on:
      - Eureka
      - db-mysql
  Foyer:
    container_name: Foyer
    build: .\foyer-ms
    ports:
      - "3083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/foyer-ms?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/

    image: "foyer-ms"
    restart: unless-stopped
    depends_on:
      - Eureka
      - db-mysql
  Bloc:
    container_name: Bloc
    build: .\BlocMS
    ports:
      - "3084:8084"
    environment:
      #port 8082
      - SERVER_PORT=8084
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "bloc-ms"
    restart: unless-stopped
  Chambre:
    container_name: Chambre
    build: .\chambre-ms
    ports:
      - "3085:8085"
    environment:
      #port 8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/chambre-ms?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "chambre-ms"
    restart: unless-stopped
  Reclamation:
    container_name: Reclamation
    build: .\reclamation-ms
    ports:
      - "3087:8087"
    environment:
      - SERVER_PORT=8087
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "reclamation-ms"
    restart: unless-stopped