version: "3.9"
services:
  db-mysql:
      image: "mysql:5.6"
      container_name: db-mysql 
      environment:
        - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
        #- MYSQL_DATABASE=job
      ports:
        - "3306:3306"
      restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8306:80"
    links:
      - db-mysql:db
    depends_on:
      - db-mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    hostname: keycloakauth
    ports:
      - "8080:8080"
    environment:
      # port 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
  Gateway:
    container_name: Gateway
    image: "gateway"
    build: .\gateway
    ports:
      - "8081:8081"
    environment:
      # port 8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloakauth:8080/realms/Enigma
    depends_on:
      - "Eureka"
      - "Foyer"
      - "Universite"
      - "keycloak"
      # - "db-mysql"
  Universite:
    container_name: Universite
    build: .\universite-ms
    ports:
      - "3082:8082"  
    environment:
      #port 8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/universite-ms?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/      
      
      
    image: "universite-ms"
    restart: unless-stopped
    depends_on:
      - Eureka
      - db-mysql
  Foyer:
    container_name: Foyer
    build: .\foyer-ms
    ports:
      - "3083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/foyer-ms?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/      
      
    image: "foyer-ms"
    restart: unless-stopped
    depends_on:
      - Eureka
      - db-mysql
  Eureka:
    container_name: eureka
    build: .\eurekaDiscov
    hostname: serviceregistry
    ports:
      - "8761:8761"   
    image: "eureka"

    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
